GET http://localhost:3000/register-vscode
// VScode check route to get the info of all the users

###

// VScode route to ensure that the login info is present in database and display status success
POST http://localhost:3000/login-vscode
Content-Type: application/json

{
    "username" : "joros",
    "password" : "jojo"
}

###

//route to ensure that the user is registered and then redirect to home page
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "vis",
    "password" : "vvv"
}

###

// VSCode check route to fill the register form in vscode routes.rest
POST http://localhost:3000/register-vscode
Content-Type: application/json

{
    "name" : "JoroBunty",
    "username" : "jorosp",
    "email" : "joro@jo",
    "password" : "jojo",
    "subscribeDate :" : ""
}

###

//passport login vscode
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "visi",
    "password" : "vviv"
}

###

//logout
DELETE http://localhost:3000/logout

//------------------------------------------------

###

GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

# {
#     "cars.name" : "car-5",
#     "cars.location" : "www.ww.com",
#     "cars.price" : 444,
#     "bikes.name" : "bike-5",
#     "bikes.location" : "www.ww.com",
#     "bikes.price" : 3333
# }

{
        "name" : "Car-5",
        "location" : "ww.ww.com",
        "price" : 444
}



# {
#     "cars" : [{
#         "name" : "Car-5",
#         "location" : "ww.ww.com",
#         "price" : 444
#     }],
#     "bikes" : [{
#         "name" : "bike-5",
#         "location" : "ww.ww.com",
#         "price" : 444
#     }]
# }